---
title: NYT Covid cases
author: Your name
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)

# Parameters
  # To get these URLs, I:
    # Step 1: Go here: https://github.com/nytimes/covid-19-data
    # Step 2: Click on the CSV file 
    # Step 3: Click "Raw" or "View raw"
    # Step 4: Copy the URL
  # URL for the county data
url_counties <- 
  "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
  # URl for the state data
url_states <- 
  "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"
file_population <- "data/populations.csv"
NYC_POPULATION <- 8398748
#===============================================================================

counties <-
  url_counties %>% 
  read_csv() 

states <-
  url_states %>% 
  read_csv()

population <-
  file_population %>% 
  read_csv(
    col_types =
      cols(
        region = col_character(),
        fips = col_character(),
        population = col_double()
      )
  )
```

## States

### Summary

```{r}
summary(states)
```

### Check for problems 

Missing values, errors, etc.

```{r}

```


## Counties

### Glimpse and summary

```{r}
glimpse(counties)
```

```{r}
summary(counties)
```

### Check for problems

## Visualizations

### U.S. 

```{r}
us <-
  states %>% 
  group_by(date) %>% 
  summarize(cases = sum(cases))

us_daily <-
  us %>% 
  mutate(new_cases = cases - lag(cases, order_by = date)) 
```

```{r}
us_daily %>% 
  drop_na(new_cases) %>% 
  ggplot(aes(date, new_cases)) +
  geom_col()
```



### States

```{r}
states_latest <-
  states %>% 
  group_by(fips) %>% 
  filter(date == max(date)) %>% 
  ungroup() %>% 
  left_join(population %>% select(-region), by = "fips")
```

```{r fig.asp=0.9}
# distribution
states_latest %>% 
  mutate(state = fct_reorder(state, cases)) %>% 
  ggplot(aes(cases, state)) +
  geom_point()
```


### Counties

```{r}
counties_latest <-
  counties %>%
  drop_na(fips) %>%
  group_by(fips) %>%
  filter(date == max(date)) %>%
  ungroup() %>%
  left_join(population %>% select(-region), by = "fips") #%>% 
  # mutate(
  #   population = if_else(county == "New York City", NYC_POPULATION, population),
  #   cases_per_100 = (cases / population) * 100
  # ) %>% 
  # drop_na(population)
```

```{r}
# counties_latest %>% 
#   ggplot(aes(cases_per_100)) +
#   geom_histogram()
```


```{r}
# counties_latest %>% 
#   mutate(cases_per_100 = (cases / population) * 100) %>% 
#   top_n(n = 30, wt = cases_per_100) 
```



